<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNL6OIoN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNL6OIoN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNL6OIoN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNL6OIoN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNL6OIoN\App_KernelDevDebugContainer([
    'container.build_hash' => 'NL6OIoN',
    'container.build_id' => 'e6808358',
    'container.build_time' => 1768485302,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNL6OIoN');
