<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_media_user' => [[], ['_controller' => 'App\\Controller\\MediaController::createMedia'], [], [['text', '/api/media']], [], [], []],
    'app_test' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/test']], [], [], []],
    'api_create_user' => [[], ['_controller' => 'App\\Controller\\UserController::createUser'], [], [['text', '/api/users']], [], [], []],
    'App\Controller\MediaController::createMedia' => [[], ['_controller' => 'App\\Controller\\MediaController::createMedia'], [], [['text', '/api/media']], [], [], []],
    'App\Controller\TestController::index' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/test']], [], [], []],
    'App\Controller\UserController::createUser' => [[], ['_controller' => 'App\\Controller\\UserController::createUser'], [], [['text', '/api/users']], [], [], []],
];
