/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TasseRouteImport } from './routes/tasse'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SacRouteImport } from './routes/sac'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NewsRouteImport } from './routes/news'
import { Route as FitRouteImport } from './routes/fit'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TasseRoute = TasseRouteImport.update({
  id: '/tasse',
  path: '/tasse',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SacRoute = SacRouteImport.update({
  id: '/sac',
  path: '/sac',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const FitRoute = FitRouteImport.update({
  id: '/fit',
  path: '/fit',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connexion': typeof ConnexionRoute
  '/fit': typeof FitRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/sac': typeof SacRoute
  '/store': typeof StoreRoute
  '/tasse': typeof TasseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connexion': typeof ConnexionRoute
  '/fit': typeof FitRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/sac': typeof SacRoute
  '/store': typeof StoreRoute
  '/tasse': typeof TasseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/connexion': typeof ConnexionRoute
  '/fit': typeof FitRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/sac': typeof SacRoute
  '/store': typeof StoreRoute
  '/tasse': typeof TasseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/connexion'
    | '/fit'
    | '/news'
    | '/register'
    | '/sac'
    | '/store'
    | '/tasse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/connexion'
    | '/fit'
    | '/news'
    | '/register'
    | '/sac'
    | '/store'
    | '/tasse'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/connexion'
    | '/fit'
    | '/news'
    | '/register'
    | '/sac'
    | '/store'
    | '/tasse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ConnexionRoute: typeof ConnexionRoute
  FitRoute: typeof FitRoute
  NewsRoute: typeof NewsRoute
  RegisterRoute: typeof RegisterRoute
  SacRoute: typeof SacRoute
  StoreRoute: typeof StoreRoute
  TasseRoute: typeof TasseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tasse': {
      id: '/tasse'
      path: '/tasse'
      fullPath: '/tasse'
      preLoaderRoute: typeof TasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sac': {
      id: '/sac'
      path: '/sac'
      fullPath: '/sac'
      preLoaderRoute: typeof SacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fit': {
      id: '/fit'
      path: '/fit'
      fullPath: '/fit'
      preLoaderRoute: typeof FitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ConnexionRoute: ConnexionRoute,
  FitRoute: FitRoute,
  NewsRoute: NewsRoute,
  RegisterRoute: RegisterRoute,
  SacRoute: SacRoute,
  StoreRoute: StoreRoute,
  TasseRoute: TasseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
